options: 
  logging: CLOUD_LOGGING_ONLY
steps:
  # STEP 1 
  # using code build internal command to build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'ashuwebapp:v1', '.']
  # Step 2 
  # creating container 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-idt', '--name', 'ashuc11',
     '-p' ,'1234:80', '--rm' ,'ashuwebapp:v1'
    ]